# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:34:52+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from pydantic import conint

from models import (
    ConversationsConversationIdEventsGetResponse,
    ConversationsConversationIdMembersGetResponse,
    ConversationsGetResponse,
    Order,
    UsersGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'devrel@vonage.com',
        'name': 'Vonage DevRel',
        'url': 'https://developer.nexmo.com/',
    },
    description='The Conversation API enables you to build conversation features where communication can take place across multiple mediums including IP Messaging, PSTN Voice, SMS and WebRTC Audio and Video. The context of the conversations is maintained though each communication event taking place within a conversation, no matter the medium.',
    title='Conversation API',
    version='1.0.1',
    servers=[{'url': 'https://api.nexmo.com/v0.2'}],
)


@app.get(
    '/conversations',
    description=""" Please note that not all data is available in the list endpoint. Once 
you've identified the conversation you need to work with, use the 
[GET /conversations/:id](#get-conversation) endpoint to fetch all of the conversation details
 """,
    tags=['conversation_management'],
)
def get_conversations(
    page_size: Optional[conint(le=100)] = 10,
    order: Optional[Order] = 'asc',
    cursor: Optional[str] = None,
    date_start: Optional[str] = None,
    date_end: Optional[str] = None,
):
    """
    List Conversations
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/conversations/{conversation_id}/events',
    tags=['conversation_management', 'event_tracking'],
)
def get_events(
    conversation_id: str,
    page_size: Optional[conint(le=100)] = 10,
    order: Optional[Order] = 'asc',
    cursor: Optional[str] = None,
    start_id: Optional[str] = None,
    end_id: Optional[str] = None,
    event_type: Optional[str] = None,
):
    """
    List Events
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/conversations/{conversation_id}/members',
    tags=['conversation_management', 'user_directory_operations'],
)
def get_members(
    conversation_id: str,
    page_size: Optional[conint(le=100)] = 10,
    order: Optional[Order] = 'asc',
    cursor: Optional[str] = None,
):
    """
    List Members
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/users', tags=['user_directory_operations'])
def get_users(
    page_size: Optional[conint(le=100)] = 10,
    order: Optional[Order] = 'asc',
    cursor: Optional[str] = None,
):
    """
    List Users
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
