# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:34:52+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class ConversationDisplayName(RootModel[str]):
    root: str = Field(
        ...,
        description='The public facing name of the conversation',
        examples=['Conversation with Ashley'],
    )


class ConversationId(RootModel[str]):
    root: str = Field(
        ...,
        description='Automatically generated conversation ID',
        examples=['CON-c4724477-72ac-438e-9fc0-1d3e2ff8728c'],
    )


class ConversationImageUrl(RootModel[str]):
    root: str = Field(
        ...,
        description='An image URL that you associate with the conversation',
        examples=['https://example.com/my-image.png'],
    )


class Self(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations/CON-c4724477-72ac-438e-9fc0-1d3e2ff8728c'
        ],
    )


class FieldLinks(BaseModel):
    self: Optional[Self] = None


class Timestamp(BaseModel):
    created: Optional[str] = Field(
        None,
        description='The time that the conversation was created',
        examples=['2019-09-03T18:40:24.324Z'],
    )


class ConversationName(RootModel[str]):
    root: str = Field(
        ...,
        description='Your internal conversation name. Must be unique',
        examples=['my-conversation'],
    )


class Self1(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations/CON-92a44c64-7e4e-485f-a0c4-1f2adfc44625/events/9'
        ],
    )


class FieldLinks1(BaseModel):
    self: Optional[Self1] = None


class Event(BaseModel):
    field_links: Optional[FieldLinks1] = Field(None, alias='_links')
    from_: Optional[str] = Field(
        None,
        alias='from',
        description='The member ID of the sender',
        examples=['MEM-afe887d8-d587-4280-9aae-dfa4c9227d5e'],
    )
    id: Optional[int] = Field(None, description='The ID of the event', examples=[9])
    timestamp: Optional[str] = Field(
        None,
        description='The time that the event happened',
        examples=['2019-09-12T19:49:21.823Z'],
    )


class Type(Enum):
    app = 'app'


class Channel(BaseModel):
    type: Optional[Type] = Field(
        None, description='The channel that the member joins with', examples=['app']
    )


class Invited(BaseModel):
    is_system: Optional[bool] = Field(None, examples=[True])


class Joined(BaseModel):
    is_system: Optional[bool] = Field(None, examples=[True])


class Initiator(BaseModel):
    invited: Optional[Invited] = None
    joined: Optional[Joined] = None


class AudioSettings(BaseModel):
    earmuffed: Optional[bool] = Field(
        None, description='Can the member hear other participants?', examples=[False]
    )
    enabled: Optional[bool] = Field(
        None, description='Is audio enabled?', examples=[False]
    )
    muted: Optional[bool] = Field(
        None,
        description='Can the member speak to other participants?',
        examples=[False],
    )


class Media(BaseModel):
    audio_settings: Optional[AudioSettings] = Field(
        None, description='The current audio state for the member'
    )


class Timestamp1(BaseModel):
    invited: Optional[str] = Field(
        None,
        description='The time that an invitation was sent',
        examples=['2019-09-03T18:40:24.324Z'],
    )
    joined: Optional[str] = Field(
        None,
        description='The time that the conversation was joined',
        examples=['2019-09-12T16:27:07.450Z'],
    )
    left: Optional[str] = Field(
        None,
        description='The time that the member left the conversation',
        examples=['2019-09-13T02:16:55.390Z'],
    )


class Self2(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations/CON-92a44c64-7e4e-485f-a0c4-1f2adfc44625/members/MEM-e784d5d1-dff2-424a-9de7-bc34f1901177'
        ],
    )


class FieldLinks2(BaseModel):
    self: Optional[Self2] = None


class State(Enum):
    INVITED = 'INVITED'
    JOINED = 'JOINED'


class MemberList(BaseModel):
    field_links: Optional[FieldLinks2] = Field(None, alias='_links')
    display_name: Optional[str] = Field(
        None, description='The display name of the User', examples=['Ashley Arthur']
    )
    id: Optional[str] = Field(
        None,
        description='Member ID',
        examples=['MEM-afe887d8-d587-4280-9aae-dfa4c9227d5e'],
    )
    name: Optional[str] = Field(
        None, description='The name of the User', examples=['ashley']
    )
    state: Optional[State] = Field(
        None,
        description='The state that the member is in for this conversation',
        examples=['JOINED'],
    )
    user_id: Optional[str] = Field(
        None,
        description='The ID of the User',
        examples=['USR-2c52f0ec-7a48-4b52-9d47-df47482b2b7e'],
    )


class Body(BaseModel):
    text: Optional[str] = Field(
        None, description='The text sent in this event', examples=['Hello World']
    )


class TextEvent(Event):
    body: Optional[Body] = Field(None, description='The body of the `text` event')
    conversation_id: Optional[str] = Field(
        None,
        description='The ID of the Conversation that the member belongs to',
        examples=['CON-92a44c64-7e4e-485f-a0c4-1f2adfc44625'],
    )
    type: Optional[str] = Field(
        None, description='The event type (`text`)', examples=['text']
    )


class UserId(RootModel[str]):
    root: str = Field(
        ...,
        description='The ID of the user',
        examples=['USR-e46d9542-752a-4786-8f12-25a2e623a793'],
    )


class Self3(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/users/USR-e46d9542-752a-4786-8f12-25a2e623a793'
        ],
    )


class UserLinks(BaseModel):
    self: Optional[Self3] = None


class UserName(RootModel[str]):
    root: str = Field(..., description='The name of the user', examples=['ashley'])


class Order(Enum):
    asc = 'asc'
    desc = 'desc'


class First(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=['https://api.nexmo.com/v0.2/conversations?order=desc&page_size=10'],
    )


class Next(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations?order=desc&page_size=10&cursor=88b395c167da4d94e929705cbd63b829a650e69a39197bfd4c949f4243f60dc4babb696afa404d2f44e7775e32b967f2a1a0bb8fb259c0999ba5a4e501eaab55'
        ],
    )


class Prev(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations?order=desc&page_size=10&cursor=069626a3de11d2ec900dff5042197bd75f1ce41dafc3f2b2481eb9151086e59aae9dba3e3a8858dc355232d499c310fbfbec43923ff657c0de8d49ffed9f7edb'
        ],
    )


class Self4(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations?order=desc&page_size=10&cursor=88b395c167da4d94e929705cbd63b82973771e7d390d274a58e301386d5762600a3ffd799bfb3fc5190c5a0d124cdd0fc72fe6e450506b18e4e2edf9fe84c7a0'
        ],
    )


class FieldLinks3(BaseModel):
    first: Optional[First] = None
    next: Optional[Next] = None
    prev: Optional[Prev] = None
    self: Optional[Self4] = None


class First1(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations/CON-92a44c64-7e4e-485f-a0c4-1f2adfc44625/events?page_size=10'
        ],
    )


class Next1(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations/CON-92a44c64-7e4e-485f-a0c4-1f2adfc44625/events?page_size=10&cursor=4db03d9254d1cdaecc7b1fc15b6bf1a81f3d3151191d784f1327893f8dc96416'
        ],
    )


class Prev1(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations/CON-92a44c64-7e4e-485f-a0c4-1f2adfc44625/events?page_size=10&cursor=84963f79fd25785be9706bd38bfd30c264f71964fa4edc8d8b4dd5f30bbd9f7c'
        ],
    )


class Self5(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/conversations/CON-92a44c64-7e4e-485f-a0c4-1f2adfc44625/events?page_size=10&cursor=a30e3b7a3dcda1434f64bbb1a5fa489b'
        ],
    )


class FieldLinks4(BaseModel):
    first: Optional[First1] = None
    next: Optional[Next1] = None
    prev: Optional[Prev1] = None
    self: Optional[Self5] = None


class Data2(BaseModel):
    members: Optional[List[MemberList]] = Field(
        None, description='List of members matching the provided filter'
    )


class FieldEmbedded2(BaseModel):
    data: Optional[Data2] = None


class First2(BaseModel):
    href: Optional[str] = Field(
        None, examples=['https://api.nexmo.com/v0.2/members?order=desc&page_size=10']
    )


class Next2(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/members?order=desc&page_size=10&cursor=88b395c167da4d94e929705cbd63b829a650e69a39197bfd4c949f4243f60dc4babb696afa404d2f44e7775e32b967f2a1a0bb8fb259c0999ba5a4e501eaab55'
        ],
    )


class Prev2(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/members?order=desc&page_size=10&cursor=069626a3de11d2ec900dff5042197bd75f1ce41dafc3f2b2481eb9151086e59aae9dba3e3a8858dc355232d499c310fbfbec43923ff657c0de8d49ffed9f7edb'
        ],
    )


class Self6(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/members?order=desc&page_size=10&cursor=88b395c167da4d94e929705cbd63b82973771e7d390d274a58e301386d5762600a3ffd799bfb3fc5190c5a0d124cdd0fc72fe6e450506b18e4e2edf9fe84c7a0'
        ],
    )


class FieldLinks5(BaseModel):
    first: Optional[First2] = None
    next: Optional[Next2] = None
    prev: Optional[Prev2] = None
    self: Optional[Self6] = None


class ConversationsConversationIdMembersGetResponse(BaseModel):
    field_embedded: Optional[FieldEmbedded2] = Field(None, alias='_embedded')
    field_links: Optional[FieldLinks5] = Field(None, alias='_links')
    page_size: Optional[int] = Field(
        None, description='The number of results returned on this page', examples=[10]
    )


class First3(BaseModel):
    href: Optional[str] = Field(
        None, examples=['https://api.nexmo.com/v0.2/users?order=desc&page_size=10']
    )


class Next3(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/users?order=desc&page_size=10&cursor=88b395c167da4d94e929705cbd63b829a650e69a39197bfd4c949f4243f60dc4babb696afa404d2f44e7775e32b967f2a1a0bb8fb259c0999ba5a4e501eaab55'
        ],
    )


class Prev3(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/users?order=desc&page_size=10&cursor=069626a3de11d2ec900dff5042197bd75f1ce41dafc3f2b2481eb9151086e59aae9dba3e3a8858dc355232d499c310fbfbec43923ff657c0de8d49ffed9f7edb'
        ],
    )


class Self7(BaseModel):
    href: Optional[str] = Field(
        None,
        examples=[
            'https://api.nexmo.com/v0.2/users?order=desc&page_size=10&cursor=88b395c167da4d94e929705cbd63b82973771e7d390d274a58e301386d5762600a3ffd799bfb3fc5190c5a0d124cdd0fc72fe6e450506b18e4e2edf9fe84c7a0'
        ],
    )


class FieldLinks6(BaseModel):
    first: Optional[First3] = None
    next: Optional[Next3] = None
    prev: Optional[Prev3] = None
    self: Optional[Self7] = None


class ConversationList(BaseModel):
    field_links: Optional[FieldLinks] = Field(None, alias='_links')
    display_name: Optional[ConversationDisplayName] = None
    id: Optional[str] = Field(
        None,
        description='The ID of the conversation',
        examples=['CON-afe887d8-d587-4280-9aae-dfa4c9227d5e'],
    )
    image_url: Optional[ConversationImageUrl] = None
    name: Optional[ConversationName] = None
    timestamp: Optional[Timestamp] = None


class CustomEvent(Event):
    body: Optional[Dict[str, Any]] = Field(
        None,
        description='The body of your `custom` event',
        examples=[{'my': 'Custom Data'}],
    )
    type: Optional[str] = Field(
        None,
        description='The event type (`custom:<YOUR_IDENTIFIER>`)',
        examples=['custom:my_event'],
    )


class Member(MemberList):
    channel: Optional[Channel] = None
    initiator: Optional[Initiator] = None
    media: Optional[Media] = Field(
        None, description='The current media state for the member'
    )
    timestamp: Optional[Timestamp1] = None


class MemberInvitedEvent(Event):
    type: Optional[str] = Field(
        None,
        description='The event type (`member:invited`)',
        examples=['member:invited'],
    )
    body: Optional[Member] = None


class MemberLeftEvent(Event):
    type: Optional[str] = Field(
        None, description='The event type (`member:left`)', examples=['member:left']
    )
    body: Optional[Member] = None


class UserList(BaseModel):
    field_links: Optional[UserLinks] = Field(None, alias='_links')
    id: Optional[UserId] = None
    name: Optional[UserName] = None


class Data(BaseModel):
    conversations: Optional[List[ConversationList]] = Field(
        None, description='List of conversations matching the provided filter'
    )


class FieldEmbedded(BaseModel):
    data: Optional[Data] = None


class ConversationsGetResponse(BaseModel):
    field_embedded: Optional[FieldEmbedded] = Field(None, alias='_embedded')
    field_links: Optional[FieldLinks3] = Field(None, alias='_links')
    cursor: Optional[str] = Field(
        None,
        description='Current cursor',
        examples=[
            '88b395c167da4d94e929705cbd63b82973771e7d390d274a58e301386d5762600a3ffd799bfb3fc5190c5a0d124cdd0fc72fe6e450506b18e4e2edf9fe84c7a0'
        ],
    )
    page_size: Optional[int] = Field(
        None, description='The number of results returned on this page.', examples=[10]
    )


class Data3(BaseModel):
    users: Optional[List[UserList]] = Field(
        None, description='List of users matching the provided filter'
    )


class FieldEmbedded3(BaseModel):
    data: Optional[Data3] = None


class UsersGetResponse(BaseModel):
    field_embedded: Optional[FieldEmbedded3] = Field(None, alias='_embedded')
    field_links: Optional[FieldLinks6] = Field(None, alias='_links')
    cursor: Optional[str] = Field(
        None,
        description='Current cursor',
        examples=[
            '88b395c167da4d94e929705cbd63b82973771e7d390d274a58e301386d5762600a3ffd799bfb3fc5190c5a0d124cdd0fc72fe6e450506b18e4e2edf9fe84c7a0'
        ],
    )
    page_size: Optional[int] = Field(
        None, description='The number of results returned on this page', examples=[10]
    )


class AllEvents(
    RootModel[Union[TextEvent, CustomEvent, MemberInvitedEvent, MemberLeftEvent]]
):
    root: Union[TextEvent, CustomEvent, MemberInvitedEvent, MemberLeftEvent]


class Data1(BaseModel):
    events: Optional[List[AllEvents]] = Field(
        None, description='List of events matching the provided filter'
    )


class FieldEmbedded1(BaseModel):
    data: Optional[Data1] = None


class ConversationsConversationIdEventsGetResponse(BaseModel):
    field_embedded: Optional[FieldEmbedded1] = Field(None, alias='_embedded')
    field_links: Optional[FieldLinks4] = Field(None, alias='_links')
    page_size: Optional[int] = Field(
        None, description='The number of results returned on this page.', examples=[10]
    )
